server:
  port: 8083

spring:
  application:
    name: enrollment-service
  data:
    mongodb:
      uri: "mongodb+srv://admin:redhat123@cluster0.wjo6wxc.mongodb.net/cb_auth?authSource=admin&retryWrites=true&w=majority&appName=Cluster0"

jwt:
  secret: ${JWT_SECRET:CloudBlitzJWTSecretKeyForSecureAuthentication2024!@#}

logging:
  level:
    in.cloudblitz.enrollment: DEBUG
