server:
  port: 8082

spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: "mongodb+srv://admin:redhat123@cluster0.wjo6wxc.mongodb.net/cb_auth?authSource=admin&retryWrites=true&w=majority&appName=Cluster0"

logging:
  level:
    in.cloudblitz.course: DEBUG
