apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-service
  namespace: cloudblitz
  labels:
    app: enrollment-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enrollment-service
  template:
    metadata:
      labels:
        app: enrollment-service
        version: v1
    spec:
      containers:
      - name: enrollment-service
        image: 385020026904.dkr.ecr.ap-south-1.amazonaws.com/enrol-s:latest
        ports:
        - containerPort: 8083
